print(3 != 5)

print()
print(5 == 5)
print(bool(5) == bool(5))
print(bool(5 and 5))
print(bool(5 or 5))
print(5 is 5)
print(not 5 is not 5)

print()
print(3 != 4)
print(3 < 4)
print(bool(3 and 4))
print(bool(3 or 4))
print(3 is not 4)
print(bool(3) == bool(4))

print()
print(True and True or False)
print((True) and (True or False))
print(True and True and not False)
print((not True or True) or False)
print(not True or True or False)

print()
var_1 = None
var_2 = 7
print(bool(var_1) == bool(var_2))
print(bool(var_1) > bool(var_2))
print(bool(var_1) >= bool(var_2))
print(bool(var_1) < bool(var_2))
print(bool(var_1) <= bool(var_2))
print(bool(var_1) != bool(var_2))
print(var_1 == var_2)
print(bool(var_1) or bool(var_2))
print(bool(var_1) and bool(var_2))
print(var_1 is not var_2)
print(not var_1 is var_2)
print(not var_1 is not var_2)

print()
var_3 = ""
var_4 = 10 - 1
print(bool(var_3) == bool(var_4))
print(bool(var_3) > bool(var_4))
print(bool(var_3) >= bool(var_4))
print(bool(var_3) < bool(var_4))
print(bool(var_3) <= bool(var_4))
print(bool(var_3) != bool(var_4))
print(var_3 == var_4)
print(bool(var_3) or bool(var_4))
print(bool(var_3) and bool(var_4))
print(var_3 is not var_4)
print(not var_3 is var_4)
print(not var_3 is not var_4)
